### ISSUE TITLE
For public files, click on their link does not start download immediately

### ISSUE THREAD

**Issue by ghorbani-mohammad** [theriverman/django-minio-backend#22]
Hello,

In Django admin, for private files clicking on the file link immediately starts to download the file. But for public files clicking on the link transfer user to the Minio dashboard. The user has to click on the download button to download the file. 

I want links for public files to be the same as private files. (immediately start download after clicking on them)
How can I achieve this?

Thanks.

**Comment by theriverman** [comment]
Hi,

It's hard to tell what's causing this odd behaviour in your setup.
I have just tested this in a newly created developer environment ( see file [CONTRIBUTE.md](../blob/master/CONTRIBUTE.md) for instructions) and it works fine for both public and private buckets.

Please use the example application ( [DjangoExampleApplication/models.py](../blob/master/DjangoExampleApplication/models.py) ) as reference to correctly implement your models and their respective admin ( [DjangoExampleApplication/admin.py](../blob/master/DjangoExampleApplication/admin.py) ) fields.

If it's still not working, please tell a bit more about your environment:

- What version of MinIO are you using?
- Is MinIO behind a reverse proxy? If yes, what's the proxy's configuration?
- What does your `pip list` command return?

Please make sure you've pulled the latest repo, because I've just pushed a correction commit to master to fix a refactoring error in DjangoExampleApplication.

**Comment by theriverman** [comment]
Hi @ghorbani-mohammad

It's hard to tell what's causing this odd behaviour in your setup.
I have just tested this in a newly created developer environment ( see file [CONTRIBUTE.md](../blob/master/CONTRIBUTE.md) for instructions) and it works fine for both public and private buckets.

Please use the example application ( [DjangoExampleApplication/models.py](../blob/master/DjangoExampleApplication/models.py) ) as reference to correctly implement your models and their respective admin ( [DjangoExampleApplication/admin.py](../blob/master/DjangoExampleApplication/admin.py) ) fields.

If it's still not working, please tell a bit more about your environment:

- What version of MinIO are you using?
- Is MinIO behind a reverse proxy? If yes, what's the proxy's configuration?
- What does your `pip list` command return?

Please make sure you've pulled the latest repo, because I've just pushed a correction commit to master to fix a refactoring error in DjangoExampleApplication.

**Comment by ghorbani-mohammad** [comment]
Thank you, @theriverman, for the reply. My model is in the below picture. So you think this model is not correctly implemented?

I saw your model example. You put some functions and property in the model. Do I need to put those in my model?

![image](https://user-images.githubusercontent.com/12118217/119223413-904f8980-bb0e-11eb-869d-3ed4a2bfa725.png)

**Comment by theriverman** [comment]
Your model looks good.

I have a feeling the problem is not in Django but maybe in MinIO or your proxy (if you're using any).
Could you clone the latest version of this repo and follow all steps in [CONTRIBUTE.md](../blob/master/CONTRIBUTE.md), please?
Don't forget adding your own MinIO connection details in `DjangoExampleProject/settings.py`.

Then just go to the admin page, add a private and a public file, and see if the generated URL works.
If they're OK, the problem is probably in your Django application.
If they're broken, the problem is either in MinIO or somewhere along the way between Django and MinIO.

Let me know of your results!

**Comment by theriverman** [comment]
I'm closing this issue now due to inactivity. Please feel free to reopen if you're problem still persists.
