### ISSUE TITLE
Inconsistent use of `MINIO_USE_HTTPS`

### ISSUE THREAD

**Issue by abhi1693** [theriverman/django-minio-backend#33]
@theriverman When I had proposed changes in #31, I had done so thinking `USE_HTTPS` variable means that the user wants `https` protocol meaning it is `False` by default. I had seen a similar assumption from you at https://github.com/theriverman/django-minio-backend/blob/96e47da87d93d5524e842ffa3b0dd936a7fd5b08/django_minio_backend/models.py#L92

But by checking it for a value of `None`, you are also enforcing on the user to set this value even though it should be a default `False` when not provided as mentioned above.

IMHO, you should leave `MINIO_USE_HTTPS` out of validate_settings unless the user wants an HTTPS connection as, without it, you are anyway using `http` as a fallback.
https://github.com/theriverman/django-minio-backend/blob/8a474149a613a0a94eef3944eb72f3ff89b46ec9/django_minio_backend/models.py#L96

**Comment by theriverman** [comment]
>  I had seen a similar assumption from you at

That is indeed a very good catch from you. I had been thinking about this a lot and I didn't clean up my mess consistently.

So, my way of thinking is that I prefer having the settings explicit instead of implicit. I want **django-minio-backend** to behave as predictable as possible, and for that, it shouldn't have default values defined for important things like SSL/TLS.
So enforcing the user to set this value is very much intentional: make sure they're aware of what's going to happen under the hood.

> you are anyway using http as a fallback.

The code fragment you're referring from line 96 is not a fallback option but an in-line decision making of what protocol prefix to use for URL generation and availability test. Earlier in the execution I'm enforcing the user to explicitly state whether they want HTTPS or not so this line -hopefully- does not act as a fallthrough case.
